services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - UID=1000
        - GID=1000
    tty: true
    volumes:
      - .:/home/user/pypleiades
    working_dir: /home/user/pypleiades
