services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - .:/pleiades-dev
    environment:
      - PLEIADES_URL=https://pleiades.cloud/api/v0.5
