ARG PYTHON_VERSION=3.10

FROM astral/uv:python${PYTHON_VERSION}-bookworm

ARG UID
ARG GID

RUN groupadd user --gid ${GID} && \
    useradd user --uid ${UID} --gid ${GID} --shell /bin/bash --create-home

USER user
WORKDIR /home/user

ENTRYPOINT [ "/bin/bash" ]
