# coding: utf-8

# flake8: noqa
"""
    MEC-RM API

    This is the MEC Recource Manager API specification.  Current Version: v0.5.0.2 (Major: 0.5, Minor: 0, Patch: 2)  As a general-purpose stateless middleware, we have designed this system with a high level of flexibility. There is no predefined API invocation flow in this system. Application developers have the freedom to creatively develop different invocation flows based on their specific needs. In fact, this application-centric flexible development is what we advocate and one of the main driving forces behind our transition from RPC-based APIs to stateless APIs.  The document covers not-fixed fields which may not compatable between versions. (espesilly version change greater than minor version)  For implement of non-published APIs, you can reference the source code by your own responsibility.  ## Documents: * [API Document](https://mecdoc.dolylab.cc/)  # noqa: E501

    OpenAPI spec version: v0.5.0.2
    Contact: nb22509@shibaura-it.ac.jp
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.request_file_upload_multi_part import RequestFileUploadMultiPart
from swagger_client.models.request_function_create import RequestFunctionCreate
from swagger_client.models.request_job_create import RequestJobCreate
from swagger_client.models.request_job_update import RequestJobUpdate
from swagger_client.models.request_worker_contract import RequestWorkerContract
from swagger_client.models.request_worker_regist import RequestWorkerRegist
from swagger_client.models.response_data_meta import ResponseDataMeta
from swagger_client.models.response_data_upload import ResponseDataUpload
from swagger_client.models.response_error import ResponseError
from swagger_client.models.response_function_create import ResponseFunctionCreate
from swagger_client.models.response_function_info import ResponseFunctionInfo
from swagger_client.models.response_job_create import ResponseJobCreate
from swagger_client.models.response_job_info import ResponseJobInfo
from swagger_client.models.response_ping_pong import ResponsePingPong
from swagger_client.models.response_worker_contract import ResponseWorkerContract
from swagger_client.models.response_worker_info import ResponseWorkerInfo
from swagger_client.models.response_worker_regist import ResponseWorkerRegist
