# coding: utf-8

"""
    MEC-RM API

    This is the MEC Recource Manager API specification.  Current Version: v0.5.0.2 (Major: 0.5, Minor: 0, Patch: 2)  As a general-purpose stateless middleware, we have designed this system with a high level of flexibility. There is no predefined API invocation flow in this system. Application developers have the freedom to creatively develop different invocation flows based on their specific needs. In fact, this application-centric flexible development is what we advocate and one of the main driving forces behind our transition from RPC-based APIs to stateless APIs.  The document covers not-fixed fields which may not compatable between versions. (espesilly version change greater than minor version)  For implement of non-published APIs, you can reference the source code by your own responsibility.  ## Documents: * [API Document](https://mecdoc.dolylab.cc/)  # noqa: E501

    OpenAPI spec version: v0.5.0.2
    Contact: nb22509@shibaura-it.ac.jp
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RequestWorkerRegist(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'runtimes': 'list[str]'
    }

    attribute_map = {
        'runtimes': 'runtimes'
    }

    def __init__(self, runtimes=None):  # noqa: E501
        """RequestWorkerRegist - a model defined in Swagger"""  # noqa: E501
        self._runtimes = None
        self.discriminator = None
        if runtimes is not None:
            self.runtimes = runtimes

    @property
    def runtimes(self):
        """Gets the runtimes of this RequestWorkerRegist.  # noqa: E501

        Runtime (interperter) list.  If no runtime given, the `default` runtime will be assigned to the worker, which should not be used by any job.  We suggest using the format of `Base[+Feature]` format here. For example, now we have a interperter called `dlabLua54`, we can append a new feature plugin to this interperter called `pcli`(pleiades client), so we should also create a runtime called `dlabLua54+pcli`  Currently our scheduler will not consider about the feature plugin, so we need to write all possible runtimes here.  Also, you can regist an non-interperter runtime, which using no lambda function as script input. See Also: `POST /lambda`  # noqa: E501

        :return: The runtimes of this RequestWorkerRegist.  # noqa: E501
        :rtype: list[str]
        """
        return self._runtimes

    @runtimes.setter
    def runtimes(self, runtimes):
        """Sets the runtimes of this RequestWorkerRegist.

        Runtime (interperter) list.  If no runtime given, the `default` runtime will be assigned to the worker, which should not be used by any job.  We suggest using the format of `Base[+Feature]` format here. For example, now we have a interperter called `dlabLua54`, we can append a new feature plugin to this interperter called `pcli`(pleiades client), so we should also create a runtime called `dlabLua54+pcli`  Currently our scheduler will not consider about the feature plugin, so we need to write all possible runtimes here.  Also, you can regist an non-interperter runtime, which using no lambda function as script input. See Also: `POST /lambda`  # noqa: E501

        :param runtimes: The runtimes of this RequestWorkerRegist.  # noqa: E501
        :type: list[str]
        """

        self._runtimes = runtimes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestWorkerRegist, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestWorkerRegist):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
