# coding: utf-8

"""
    MEC-RM API

    This is the MEC Recource Manager API specification.  Current Version: v0.5.0.2 (Major: 0.5, Minor: 0, Patch: 2)  As a general-purpose stateless middleware, we have designed this system with a high level of flexibility. There is no predefined API invocation flow in this system. Application developers have the freedom to creatively develop different invocation flows based on their specific needs. In fact, this application-centric flexible development is what we advocate and one of the main driving forces behind our transition from RPC-based APIs to stateless APIs.  The document covers not-fixed fields which may not compatable between versions. (espesilly version change greater than minor version)  For implement of non-published APIs, you can reference the source code by your own responsibility.  ## Documents: * [API Document](https://mecdoc.dolylab.cc/)  # noqa: E501

    OpenAPI spec version: v0.5.0.2
    Contact: nb22509@shibaura-it.ac.jp
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.kv_api import KVApi  # noqa: E501
from swagger_client.rest import ApiException


class TestKVApi(unittest.TestCase):
    """KVApi unit test stubs"""

    def setUp(self):
        self.api = KVApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pleades_kv_create(self):
        """Test case for pleades_kv_create

        Create new Key-Value storage domain object.  # noqa: E501
        """
        pass

    def test_pleades_kv_delete(self):
        """Test case for pleades_kv_delete

        DEL method (DELETE {key})  # noqa: E501
        """
        pass

    def test_pleades_kv_get(self):
        """Test case for pleades_kv_get

        GET method of KV storage (GET {key})  # noqa: E501
        """
        pass

    def test_pleades_kv_info(self):
        """Test case for pleades_kv_info

        Get KV-Storage object meta data  # noqa: E501
        """
        pass

    def test_pleades_kv_set(self):
        """Test case for pleades_kv_set

        SET method of KV storage (SET {key} {body})  # noqa: E501
        """
        pass

    def test_pleiades_kv_flush(self):
        """Test case for pleiades_kv_flush

        Remove all keys (FLUSH)  # noqa: E501
        """
        pass

    def test_pleiades_kv_keys(self):
        """Test case for pleiades_kv_keys

        Get all keys (KEYS)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
